title: Chinmaya Andukuri
tagline: Student at Stanford University
url: http://scandukuri.github.io
baseurl: "http://scandukuri.github.io"
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Chinmaya Andukuri
  url: http://scandukuri.github.io
  email: fred.hohman@gmail.com

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
theme: minima